In [12]:
import pandas as pd

# load imdb csv file into dataframe
imdb = pd.read_csv("./labels_adjusted_metadata.csv" )
imdb.head()

,movie_title,title_year,director_name,gross,budget,content_rating,country
0,Avatar,2009.0,James Cameron,760505847.0,237000000.0,3,USA
1,Pirates of the Caribbean: At World's End,2007.0,Gore Verbinski,309404152.0,300000000.0,3,USA
2,The Dark Knight Rises,2012.0,Christopher Nolan,448130642.0,250000000.0,3,USA
3,John Carter,2012.0,Andrew Stanton,73058679.0,263700000.0,3,USA
4,Spider-Man 3,2007.0,Sam Raimi,336530303.0,258000000.0,3,USA

In [18]:
imdb['profit'] = 0
imdb.head()

,movie_title,title_year,director_name,gross,budget,content_rating,country,profit
0,Avatar,2009.0,James Cameron,760505847.0,237000000.0,3,USA,0
1,Pirates of the Caribbean: At World's End,2007.0,Gore Verbinski,309404152.0,300000000.0,3,USA,0
2,The Dark Knight Rises,2012.0,Christopher Nolan,448130642.0,250000000.0,3,USA,0
3,John Carter,2012.0,Andrew Stanton,73058679.0,263700000.0,3,USA,0
4,Spider-Man 3,2007.0,Sam Raimi,336530303.0,258000000.0,3,USA,0

In [19]:
imdb.loc[(imdb.gross > imdb.budget), 'profit'] = 1
imdb.head(15)

,movie_title,title_year,director_name,gross,budget,content_rating,country,profit
0,Avatar,2009.0,James Cameron,760505847.0,237000000.0,3,USA,1
1,Pirates of the Caribbean: At World's End,2007.0,Gore Verbinski,309404152.0,300000000.0,3,USA,1
2,The Dark Knight Rises,2012.0,Christopher Nolan,448130642.0,250000000.0,3,USA,1
3,John Carter,2012.0,Andrew Stanton,73058679.0,263700000.0,3,USA,0
4,Spider-Man 3,2007.0,Sam Raimi,336530303.0,258000000.0,3,USA,1
5,Tangled,2010.0,Nathan Greno,200807262.0,260000000.0,2,USA,0
6,Avengers: Age of Ultron,2015.0,Joss Whedon,458991599.0,250000000.0,3,USA,1
7,Batman v Superman: Dawn of Justice,2016.0,Zack Snyder,330249062.0,250000000.0,3,USA,1
8,Superman Returns,2006.0,Bryan Singer,200069408.0,209000000.0,3,USA,0
9,Pirates of the Caribbean: Dead Man's Chest,2006.0,Gore Verbinski,423032628.0,225000000.0,3,USA,1
10,The Lone Ranger,2013.0,Gore Verbinski,89289910.0,215000000.0,3,USA,0
11,Man of Steel,2013.0,Zack Snyder,291021565.0,225000000.0,3,USA,1
12,The Chronicles of Narnia: Prince Caspian,2008.0,Andrew Adamson,141614023.0,225000000.0,2,USA,0
13,The Avengers,2012.0,Joss Whedon,623279547.0,220000000.0,3,USA,1
14,Pirates of the Caribbean: On Stranger Tides,2011.0,Rob Marshall,241063875.0,250000000.0,3,USA,0

In [20]:
#Using content rating & budget to predict if movie will be profitable
X = imdb.loc[:, ['content_rating','budget']].values 
y = imdb.loc[:, 'profit'].values 

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=8)

In [21]:
#conclusion : 52% prediction rate

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=8)
knn = KNeighborsClassifier(n_neighbors=7, algorithm='auto', metric='minkowski', p=1, weights='distance')
imdb_knn_model = knn.fit(X_train, y_train) #the model/classifier
imdb_knn_model.score(X_test, y_test)

0.52834467120181405